packages:
  - packages/*

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  sharp: true
catalog:
  playwright: latest
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: 0.2.6
  zod: latest
overrides:
  '@electron/get': 5.1.0
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
